@Artskart3.Server_HostAddress = https://localhost:5088

### Health check
GET {{Artskart3.Server_HostAddress}}/hc

### Search taxons by name (default max 20 results)
GET {{Artskart3.Server_HostAddress}}/api/Search/SearchTaxons?name=ixodes%20ricinus
X-CSRF: 1

### Search taxons by name with custom max count
GET {{Artskart3.Server_HostAddress}}/api/Search/SearchTaxons?name=ixodes%20ricinus&maxCount=5
X-CSRF: 1

### Search observation, no filters
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{}

### Search observation, filter on preferred popular name
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "preferredPopularName": "slettsnok"
}

### Search observation, filter on scientific name
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "scientificName": "Dermochelys"
}

### Search observation, filter on multiple TaxonGroupIds
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "taxonGroupIds": [1, 2, 3]
}

### Search observation, filter on multiple OrganizationIds
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "organizationIds": [1301, 1305, 3100]
}

### Search observation, filter on multiple RisikokategoriIder
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "risikokategoriIder": [1, 2, 3]
}

### Search observation, filter on multiple MunicipalityIds
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "municipalityIds": ["1101", "1145", "1260"]
}

### Search observation, all list filters combined with multiple ids
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "taxonGroupIds": [1, 2],
  "organizationIds": [10, 20],
  "risikokategoriIder": [1, 2],
  "municipalityIds": ["301", "302", "303"]
}

### Search observation, paginated
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "pageNumber": 5,
  "resultsPerPage": 30
}

### Search observation, all list filters combined with pagination
POST {{Artskart3.Server_HostAddress}}/api/Search/Observation
X-CSRF: 1
Content-Type: application/json

{
  "preferredPopularName": "slettsnok",
  "taxonGroupIds": [12],
  "organizationIds": [1997, 1998],
  "risikokategoriIder": [11],
  "municipalityIds": ["4203", "4202"],
  "pageNumber": 1,
  "resultsPerPage": 10
}


### Get observation locations (no filter)
GET {{Artskart3.Server_HostAddress}}/api/Search/Locations
X-CSRF: 1

### Get observation locations with filters
GET {{Artskart3.Server_HostAddress}}/api/Search/Locations?TaxonGroupIds=1,2&MaxResults=500&CoordinatePrecisionFrom=0&CoordinatePrecisionTo=1000
X-CSRF: 1

### Get all area markers (counties and municipalities)
GET {{Artskart3.Server_HostAddress}}/api/Search/Areas
X-CSRF: 1
  