// <auto-generated />
using System;
using Artskart3.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artskart3.Infrastructure.Migrations
{
    [DbContext(typeof(ArtskartDbContext))]
    [Migration("20260408120000_AddSearchFilterIndexes")]
    partial class AddSearchFilterIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Artskart3.Core.Domain.Entities.Observation", b =>
                {
                    b.HasIndex(new[] { "LocationId" }, "IX_Observation_LocationId");

                    b.HasIndex(new[] { "TaxonGroupId" }, "IX_Observation_TaxonGroupId");

                    b.HasIndex(new[] { "MonthCollected" }, "IX_Observation_MonthCollected");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Observation_CategoryId");

                    b.HasIndex(new[] { "BasisOfRecordId" }, "IX_Observation_BasisOfRecordId");

                    b.HasIndex(new[] { "InstitutionId" }, "IX_Observation_InstitutionId");

                    b.HasIndex(new[] { "InstitutionCode" }, "IX_Observation_InstitutionCode");

                    b.HasIndex(new[] { "YearCollected" }, "IX_Observation_YearCollected");

                    b.HasIndex(new[] { "CoordinatePrecisionInMeters" }, "IX_Observation_CoordinatePrecisionInMeters");

                    b.HasIndex(new[] { "DateLastModified" }, "IX_Observation_DateLastModified");

                    b.HasIndex(new[] { "LocationId", "HasErrors", "HasAnnotations" }, "IX_Observation_LocationId_HasErrors_HasAnnotations");

                    b.HasIndex(new[] { "YearCollected", "LocationId" }, "IX_Observation_YearCollected_LocationId");

                    b.HasIndex(new[] { "TaxonGroupId", "LocationId" }, "IX_Observation_TaxonGroupId_LocationId");
                });

#pragma warning restore 612, 618
        }
    }
}
