/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/export/csv/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExportColumnDefinition"][];
                        "application/json": components["schemas"]["ExportColumnDefinition"][];
                        "text/json": components["schemas"]["ExportColumnDefinition"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StartExportRequestDto"];
                    "text/json": components["schemas"]["StartExportRequestDto"];
                    "application/*+json": components["schemas"]["StartExportRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExportSummaryDto"];
                        "application/json": components["schemas"]["ExportSummaryDto"];
                        "text/json": components["schemas"]["ExportSummaryDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StartExportRequestDto"];
                    "text/json": components["schemas"]["StartExportRequestDto"];
                    "application/*+json": components["schemas"]["StartExportRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsvExportJobDto"];
                        "application/json": components["schemas"]["CsvExportJobDto"];
                        "text/json": components["schemas"]["CsvExportJobDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/download/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsvExportJobDto"][];
                        "application/json": components["schemas"]["CsvExportJobDto"][];
                        "text/json": components["schemas"]["CsvExportJobDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryTypeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AreaResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstitutionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    maxCount?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    maxCount?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    maxCount?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/CatalogNumbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                    maxCount?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogNumberMatchDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/TaxonGroups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaxonGroupDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Behaviors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BehaviorDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/BasisOfRecords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BasisOfRecordDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/TaxonTree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    parentTaxonId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaxonTreeNodeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/TaxonAncestry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    taxonIds?: number[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaxonAncestryDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Observation/{locationId}/{observationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    locationId: number;
                    observationId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObservationDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": number[];
                    "text/json": number[];
                    "application/*+json": number[];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ObservationListInfoDto"][];
                        "application/json": components["schemas"]["ObservationListInfoDto"][];
                        "text/json": components["schemas"]["ObservationListInfoDto"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/SearchTaxons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    name?: string;
                    maxCount?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaxonDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/Locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LocationSearchFilterDto"];
                    "text/json": components["schemas"]["LocationSearchFilterDto"];
                    "application/*+json": components["schemas"]["LocationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/Observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ObservationSearchFilterDto"];
                    "text/json": components["schemas"]["ObservationSearchFilterDto"];
                    "application/*+json": components["schemas"]["ObservationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedObservationResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/AreaMarkers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    zoomLevel?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LocationSearchFilterDto"];
                    "text/json": components["schemas"]["LocationSearchFilterDto"];
                    "application/*+json": components["schemas"]["LocationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AreaMarkerDto"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/AreaCounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    zoomLevel?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LocationSearchFilterDto"];
                    "text/json": components["schemas"]["LocationSearchFilterDto"];
                    "application/*+json": components["schemas"]["LocationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/Species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpeciesDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Gateway Timeout */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/LocationPolygons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LocationSearchFilterDto"];
                    "text/json": components["schemas"]["LocationSearchFilterDto"];
                    "application/*+json": components["schemas"]["LocationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LocationPolygonDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @enum {integer}
         */
        AlertType: 0 | 1 | 2 | 3 | 4;
        AreaDto: {
            /** Format: int32 */
            id?: number;
            fid?: string;
            name?: string;
            isCurrent?: boolean;
            /** Format: int32 */
            observationCount?: null | number;
        };
        AreaMarkerDto: {
            /** Format: int32 */
            id: number;
            documentId: string;
            fid: string;
            name: string;
            /** Format: int32 */
            areaTypeId: number;
            parentFid: string;
            /** Format: int32 */
            observationCount: number;
            wktsPolygon: null | string;
            centroid?: components["schemas"]["CentroidDto"];
        };
        AreaResponseDto: {
            counties?: components["schemas"]["AreaTypeDto"];
            municipalities?: components["schemas"]["AreaTypeDto"];
            restrictedAreas?: components["schemas"]["AreaTypeDto"];
            oceanAreas?: components["schemas"]["AreaTypeDto"];
            "svalbardBj\u00F8rn\u00F8yaAndJanMayen"?: components["schemas"]["AreaTypeDto"];
        };
        AreaTypeDto: {
            /** Format: int32 */
            id?: number;
            name?: string;
            areas?: components["schemas"]["AreaDto"][];
        };
        BasisOfRecordDto: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: null | string;
            variants?: string;
            /** Format: int32 */
            observationCount?: null | number;
        };
        BehaviorDto: {
            /** Format: int32 */
            id?: number;
            name?: string;
            variants?: string;
            /** Format: int32 */
            observationCount?: null | number;
            description?: null | string;
        };
        CatalogNumberMatchDto: {
            catalogNumber?: string;
            observationIds?: number[];
            /** Format: int32 */
            readonly observationCount?: number;
        };
        CategoryDto: {
            /** Format: int32 */
            id?: number;
            code?: string;
            name?: string;
            /** Format: int32 */
            observationCount?: null | number;
        };
        CategoryTypeDto: {
            /** Format: int32 */
            id?: number;
            name?: string;
            categories?: components["schemas"]["CategoryDto"][];
        };
        CentroidDto: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        CoordinatePrecisionDto: {
            /** Format: int32 */
            from?: null | number;
            /** Format: int32 */
            to?: null | number;
        };
        CsvExportJobDto: {
            /** Format: int32 */
            id?: number;
            name?: null | string;
            fileName?: string;
            status?: components["schemas"]["CsvExportStatus"];
            /** Format: int32 */
            totalRows?: number;
            /** Format: int32 */
            rowsProcessed?: number;
            /** Format: int64 */
            fileSize?: number;
            hasExcel?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: null | string;
            /** Format: date-time */
            completedAt?: null | string;
            /** Format: date-time */
            expiresAt?: null | string;
            errorMessage?: null | string;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        CsvExportStatus: 0 | 1 | 2 | 3 | 4;
        EnvelopeDto: {
            /** Format: double */
            minX?: number;
            /** Format: double */
            minY?: number;
            /** Format: double */
            maxX?: number;
            /** Format: double */
            maxY?: number;
            readonly isValid?: boolean;
        };
        ExportColumnDefinition: {
            name?: string;
            displayName?: string;
            isDefaultSelected?: boolean;
        };
        ExportSummaryDto: {
            /** Format: int32 */
            totalRows?: number;
            /** Format: int64 */
            estimatedFileSizeBytes?: number;
            exceedsSoftLimit?: boolean;
            exceedsHardLimit?: boolean;
            exportName?: string;
            /** Format: int32 */
            hardLimit?: number;
        };
        InstitutionDto: {
            /** Format: int32 */
            id?: number;
            name?: string;
            code?: null | string;
            /** Format: int32 */
            observationCount?: null | number;
        };
        LocationPolygonDto: {
            /** Format: int32 */
            locationId?: number;
            locality?: null | string;
            wktPolygon?: string;
            /** Format: int32 */
            observationCount?: number;
        };
        LocationSearchFilterDto: {
            taxonGroupIds?: null | number[];
            taxonIds?: null | number[];
            categoryIds?: null | number[];
            basisOfRecordIds?: null | number[];
            organizationIds?: null | number[];
            municipalityIds?: null | string[];
            countyIds?: null | string[];
            restrictedAreaIds?: null | string[];
            oceanAreaIds?: null | string[];
            behaviorIds?: null | number[];
            /** Format: int32 */
            registrationStatusId?: null | number;
            coordinatePrecision?: components["schemas"]["CoordinatePrecisionDto"];
            period?: components["schemas"]["PeriodDto"];
            /** Format: int32 */
            datasetOrgId?: null | number;
            /** Format: int32 */
            projectOrgId?: null | number;
            observationIds?: null | number[];
            withImages?: null | boolean;
            readonly hasActiveFilters?: boolean;
            readonly hasObservationAttributeFilters?: boolean;
            /** Format: int32 */
            epsg?: null | number;
            /** Format: int32 */
            maxResults?: number;
            envelope?: components["schemas"]["EnvelopeDto"];
        };
        NotificationModel: {
            type?: components["schemas"]["AlertType"];
            heading?: string;
            description?: string;
            /** Format: date-time */
            startDateTime?: null | string;
            /** Format: date-time */
            endDateTime?: null | string;
            /** Format: date */
            startDisplayDate?: null | string;
            /** Format: date */
            endDisplayDate?: null | string;
            canClose?: boolean;
        };
        ObservationDto: {
            /** Format: int32 */
            id?: number;
            preferredPopularName?: null | string;
            scientificName?: null | string;
            author?: null | string;
            institution?: null | string;
            locality?: null | string;
            municipalityId?: null | string;
            /** Format: int32 */
            taxonGroupId?: null | number;
            /** Format: int32 */
            categoryId?: null | number;
            /** Format: date-time */
            dateTimeCollected?: null | string;
            /** Format: int32 */
            coordinatePrecisionInMeters?: null | number;
        };
        ObservationListInfoDto: {
            /** Format: int32 */
            id?: number;
            preferredPopularName?: null | string;
            scientificName?: null | string;
            displayName?: string;
            author?: null | string;
            /** Format: int32 */
            taxonGroupId?: null | number;
            taxonGroupName?: null | string;
            /** Format: int32 */
            categoryId?: null | number;
            categoryName?: null | string;
            institutionId?: null | string;
            institutionName?: null | string;
            /** Format: int32 */
            locationId?: null | number;
            registrationType?: null | string[];
            collector?: null | string;
        };
        ObservationSearchFilterDto: {
            /** Format: int32 */
            pageNumber?: null | number;
            /** Format: int32 */
            resultsPerPage?: null | number;
            readonly isPaginated?: boolean;
            taxonGroupIds?: null | number[];
            taxonIds?: null | number[];
            categoryIds?: null | number[];
            organizationIds?: null | number[];
            municipalityIds?: null | string[];
            countyIds?: null | string[];
            restrictedAreaIds?: null | string[];
            oceanAreaIds?: null | string[];
            behaviorIds?: null | number[];
            basisOfRecordIds?: null | number[];
            /** Format: int32 */
            registrationStatusId?: null | number;
            coordinatePrecision?: components["schemas"]["CoordinatePrecisionDto"];
            period?: components["schemas"]["PeriodDto"];
            /** Format: int32 */
            datasetOrgId?: null | number;
            /** Format: int32 */
            projectOrgId?: null | number;
            observationIds?: null | number[];
            withImages?: null | boolean;
        };
        OrganizationDto: {
            /** Format: int32 */
            id?: number;
            name?: string;
        };
        PagedObservationResponseDto: {
            items?: null | components["schemas"]["ObservationDto"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            resultsPerPage?: number;
            /** Format: int32 */
            lookaheadCount?: number;
            hasMorePages?: boolean;
        };
        PeriodDto: {
            /** Format: int32 */
            from?: null | number;
            /** Format: int32 */
            to?: null | number;
            months?: null | number[];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        } & {
            [key: string]: unknown;
        };
        ScientificNameSynonymDto: {
            name?: string;
            nameFormatted?: string;
            author?: string;
            rank?: string;
        };
        SpeciesDto: {
            /** Format: int32 */
            taxonId?: number;
            scientificName?: string;
            scientificNameFormatted?: string;
            author?: string;
            rank?: string;
            preferredVernacularNames?: components["schemas"]["VernacularNameDto"][];
            vernacularNameSynonyms?: components["schemas"]["VernacularNameDto"][];
            scientificNameSynonyms?: components["schemas"]["ScientificNameSynonymDto"][];
        };
        StartExportRequestDto: {
            name?: null | string;
            filter?: components["schemas"]["ObservationSearchFilterDto"];
            selectedColumns?: string[];
        };
        TaxonAncestryDto: {
            /** Format: int32 */
            id?: number;
            parentIds?: number[];
            levels?: components["schemas"]["TaxonAncestryLevelDto"][];
        };
        TaxonAncestryLevelDto: {
            /** Format: int32 */
            parentId?: number;
            childIds?: number[];
        };
        TaxonDto: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            externalTaxonId?: number;
            validScientificName?: null | string;
            validScientificNameAuthorship?: null | string;
            preferredPopularName?: null | string;
            /** Format: int32 */
            taxonGroupId?: number;
            /** Format: int32 */
            taxonRankId?: number;
            /** Format: int32 */
            cumulativeObservationCount?: null | number;
            existsInCountry?: boolean;
        };
        TaxonGroupDto: {
            /** Format: int32 */
            id?: number;
            name?: string;
            /** Format: int32 */
            observationCount?: null | number;
        };
        TaxonTreeNodeDto: {
            /** Format: int32 */
            id?: number;
            validScientificName?: null | string;
            preferredPopularName?: null | string;
            /** Format: int32 */
            taxonRankId?: number;
            /** Format: int32 */
            taxonGroupId?: number;
            /** Format: int32 */
            cumulativeObservationCount?: null | number;
            existsInCountry?: boolean;
            hasChildren?: boolean;
            children?: components["schemas"]["TaxonTreeNodeDto"][];
        };
        UserDto: {
            name?: null | string;
            email?: null | string;
        };
        VernacularNameDto: {
            name?: string;
            language?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
