/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/export/csv/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExportColumnDefinition"][];
                        "application/json": components["schemas"]["ExportColumnDefinition"][];
                        "text/json": components["schemas"]["ExportColumnDefinition"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StartExportRequestDto"];
                    "text/json": components["schemas"]["StartExportRequestDto"];
                    "application/*+json": components["schemas"]["StartExportRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExportSummaryDto"];
                        "application/json": components["schemas"]["ExportSummaryDto"];
                        "text/json": components["schemas"]["ExportSummaryDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StartExportRequestDto"];
                    "text/json": components["schemas"]["StartExportRequestDto"];
                    "application/*+json": components["schemas"]["StartExportRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsvExportJobDto"];
                        "application/json": components["schemas"]["CsvExportJobDto"];
                        "text/json": components["schemas"]["CsvExportJobDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/download/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsvExportJobDto"][];
                        "application/json": components["schemas"]["CsvExportJobDto"][];
                        "text/json": components["schemas"]["CsvExportJobDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryTypeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AreaResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstitutionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/TaxonGroups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaxonGroupDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/Behaviors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BehaviorDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Lookup/BasisOfRecords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BasisOfRecordDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/SearchTaxons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    name?: string;
                    maxCount?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaxonDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/Locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LocationSearchFilterDto"];
                    "text/json": components["schemas"]["LocationSearchFilterDto"];
                    "application/*+json": components["schemas"]["LocationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/Observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ObservationSearchFilterDto"];
                    "text/json": components["schemas"]["ObservationSearchFilterDto"];
                    "application/*+json": components["schemas"]["ObservationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedObservationResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Search/AreaMarkers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    zoomLevel?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LocationSearchFilterDto"];
                    "text/json": components["schemas"]["LocationSearchFilterDto"];
                    "application/*+json": components["schemas"]["LocationSearchFilterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AreaMarkerDto"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @enum {integer}
         */
        AlertType: 0 | 1 | 2 | 3 | 4;
        AreaDto: {
            /** Format: int32 */
            id?: number;
            fid?: string | null;
            name?: string | null;
            isCurrent?: boolean;
            /** Format: int32 */
            observationCount?: number | null;
        };
        AreaMarkerDto: {
            /** Format: int32 */
            id?: number;
            documentId?: string | null;
            fid?: string | null;
            name?: string | null;
            /** Format: int32 */
            areaTypeId?: number;
            parentFid?: string | null;
            /** Format: int32 */
            observationCount?: number | null;
            wktsPolygon?: string | null;
            centroid?: components["schemas"]["CentroidDto"];
        };
        AreaResponseDto: {
            counties?: components["schemas"]["CountyDto"];
            municipalities?: components["schemas"]["AreaTypeDto"];
            restrictedAreas?: components["schemas"]["AreaTypeDto"];
            oceanAreas?: components["schemas"]["AreaTypeDto"];
        };
        AreaTypeDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            areas?: components["schemas"]["AreaDto"][] | null;
        };
        BasisOfRecordDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            description?: string | null;
            variants?: string | null;
            /** Format: int32 */
            observationCount?: number | null;
        };
        BehaviorDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            variants?: string | null;
            /** Format: int32 */
            observationCount?: number | null;
            description?: string | null;
        };
        CategoryDto: {
            /** Format: int32 */
            id?: number;
            code?: string | null;
            name?: string | null;
            /** Format: int32 */
            observationCount?: number | null;
        };
        CategoryTypeDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            categories?: components["schemas"]["CategoryDto"][] | null;
        };
        CentroidDto: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
        };
        CoordinatePrecisionDto: {
            /** Format: int32 */
            from?: number | null;
            /** Format: int32 */
            to?: number | null;
        };
        CountyDto: {
            fastlandsNorge?: components["schemas"]["AreaDto"][] | null;
            janMayen?: components["schemas"]["AreaDto"];
            svalbard?: components["schemas"]["AreaDto"];
        };
        CsvExportJobDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            fileName?: string;
            status?: components["schemas"]["CsvExportStatus"];
            /** Format: int32 */
            totalRows?: number;
            /** Format: int32 */
            rowsProcessed?: number;
            /** Format: int64 */
            fileSize?: number;
            hasExcel?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            errorMessage?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        CsvExportStatus: 0 | 1 | 2 | 3 | 4;
        EnvelopeDto: {
            /** Format: double */
            minX?: number;
            /** Format: double */
            minY?: number;
            /** Format: double */
            maxX?: number;
            /** Format: double */
            maxY?: number;
            readonly isValid?: boolean;
        };
        ExportColumnDefinition: {
            name?: string | null;
            displayName?: string | null;
            isDefaultSelected?: boolean;
        };
        ExportSummaryDto: {
            /** Format: int32 */
            totalRows?: number;
            /** Format: int64 */
            estimatedFileSizeBytes?: number;
            exceedsSoftLimit?: boolean;
            exceedsHardLimit?: boolean;
            exportName?: string | null;
            /** Format: int32 */
            hardLimit?: number;
        };
        InstitutionDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            code?: string | null;
            /** Format: int32 */
            observationCount?: number | null;
        };
        LocationSearchFilterDto: {
            taxonGroupIds?: number[] | null;
            categoryIds?: number[] | null;
            basisOfRecordIds?: number[] | null;
            registrationStatusId?: number | null;
            organizationIds?: number[] | null;
            municipalityIds?: string[] | null;
            countyIds?: string[] | null;
            restrictedAreaIds?: string[] | null;
            oceanAreaIds?: string[] | null;
            behaviorIds?: number[] | null;
            coordinatePrecision?: components["schemas"]["CoordinatePrecisionDto"];
            period?: components["schemas"]["PeriodDto"];
            readonly hasActiveFilters?: boolean;
            readonly hasObservationAttributeFilters?: boolean;
            /** Format: int32 */
            epsg?: number | null;
            /** Format: int32 */
            maxResults?: number;
            envelope?: components["schemas"]["EnvelopeDto"];
        };
        NotificationModel: {
            type?: components["schemas"]["AlertType"];
            heading?: string | null;
            description?: string | null;
            /** Format: date-time */
            startDateTime?: string | null;
            /** Format: date-time */
            endDateTime?: string | null;
            /** Format: date */
            startDisplayDate?: string | null;
            /** Format: date */
            endDisplayDate?: string | null;
            canClose?: boolean;
        };
        ObservationDto: {
            /** Format: int32 */
            id?: number;
            preferredPopularName?: string | null;
            scientificName?: string | null;
            author?: string | null;
            institution?: string | null;
            locality?: string | null;
            municipalityId?: string | null;
            /** Format: int32 */
            taxonGroupId?: number | null;
            /** Format: int32 */
            categoryId?: number | null;
            /** Format: date-time */
            dateTimeCollected?: string | null;
            /** Format: int32 */
            coordinatePrecisionInMeters?: number | null;
        };
        ObservationSearchFilterDto: {
            /** Format: int32 */
            pageNumber?: number | null;
            /** Format: int32 */
            resultsPerPage?: number | null;
            readonly isPaginated?: boolean;
            preferredPopularName?: string | null;
            scientificName?: string | null;
            author?: string | null;
            taxonGroupIds?: number[] | null;
            categoryIds?: number[] | null;
            organizationIds?: number[] | null;
            municipalityIds?: string[] | null;
            countyIds?: string[] | null;
            restrictedAreaIds?: string[] | null;
            oceanAreaIds?: string[] | null;
            behaviorIds?: number[] | null;
            basisOfRecordIds?: number[] | null;
            registrationStatusId?: number | null;
            coordinatePrecision?: components["schemas"]["CoordinatePrecisionDto"];
            period?: components["schemas"]["PeriodDto"];
        };
        PagedObservationResponseDto: {
            items?: components["schemas"]["ObservationDto"][] | null;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            resultsPerPage?: number;
            /** Format: int32 */
            lookaheadCount?: number;
        };
        PeriodDto: {
            /** Format: int32 */
            from?: number | null;
            /** Format: int32 */
            to?: number | null;
        };
        StartExportRequestDto: {
            name?: string | null;
            filter?: components["schemas"]["ObservationSearchFilterDto"];
            selectedColumns?: string[] | null;
        };
        TaxonDto: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            externalTaxonId?: number;
            validScientificName?: string | null;
            validScientificNameAuthorship?: string | null;
            preferredPopularName?: string | null;
            /** Format: int32 */
            taxonGroupId?: number;
            /** Format: int32 */
            taxonRankId?: number;
            /** Format: int32 */
            cumulativeObservationCount?: number | null;
            existsInCountry?: boolean;
        };
        TaxonGroupDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            /** Format: int32 */
            observationCount?: number | null;
        };
        UserDto: {
            name?: string | null;
            email?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
